### ISSUE TITLE
problem with input

### ISSUE THREAD

**Issue by ghost** [samjones246/exp-torus#1]
every time I try to run this script it gives out this error

![Untitled](https://user-images.githubusercontent.com/54474914/121813675-84557400-cc43-11eb-9f69-e3a5061a5ccc.png)

**Comment by samjones246** [comment]
What device are you trying to run it on?

**Comment by ghost** [comment]
I'm trying to run it on a Samsung galaxy s10

**Comment by ghost** [comment]
Nevermind I solved it
